import type { Metadata } from "next";
// Disable remote font fetching in CI environments
// If fonts are required, consider bundling locally instead of fetching at build time.
// Using system fonts to avoid network font fetching during build
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
}
